name: Deploy Panda's Blog to Pages

on:
  push:
    paths-ignore:
      - "images/**"
      - "LICENSE"
      - "README.md"
    branches:
      - master
      - exampleSite
      - main
  workflow_dispatch:
    # manual run
    inputs:
      hugoVersion:
        description: "Hugo Version"
        required: false
        default: "0.146.0"
  schedule:
    # 每小时执行一次 (UTC时间)
    - cron: '0 * * * *'

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: ${{ github.event.inputs.hugoVersion || '0.146.0' }}
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Clone panda_wiki content
        # 克隆仓库并只保留 panda-blog 文件夹
        run: |
          git clone https://github.com/wcl95716/panda_wiki.git content/posts/panda_wiki
          cd content/posts/panda_wiki && find . -mindepth 1 -maxdepth 1 ! -name 'panda-blog' -exec rm -rf {} +
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Auto-generate Front Matter
        run: |
          echo "🔧 开始自动生成 Front Matter..."
          echo "📁 当前工作目录: $(pwd)"
          echo "📂 检查脚本是否存在:"
          ls -la scripts/
          echo "🐍 Python 版本:"
          python3 --version
          echo "📂 检查内容目录结构:"
          find content/posts -type d | head -10
          echo "📄 检查 markdown 文件:"
          find content/posts -name "*.md" | head -5
          echo "🔍 检查Git仓库状态:"
          echo "主仓库Git状态:"
          git log --oneline -3
          echo "panda_wiki仓库Git状态:"
          cd content/posts/panda_wiki && git log --oneline -3
          cd ../../..
          echo "🚀 运行 Front Matter 生成脚本..."
          python3 scripts/enhanced_front_matter.py --force --force-git
          echo "✅ Front Matter 生成完成"
          echo "📊 显示处理后的文件:"
          find content/posts -name "*.md" -exec head -5 {} \; | head -20
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Get Theme
        run: git submodule update --init --recursive
      - name: Update theme to Latest commit
        run: git submodule update --remote --merge
      - name: Build with Hugo
        run: |
          hugo \
            --buildDrafts --gc \
            --baseURL ${{ steps.pages.outputs.base_url }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
